// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: main.proto

package mainpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UidGenerator_Uid_FullMethodName         = "/uid.UidGenerator/Uid"
	UidGenerator_HealthCheck_FullMethodName = "/uid.UidGenerator/HealthCheck"
)

// UidGeneratorClient is the client API for UidGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UidGeneratorClient interface {
	Uid(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	HealthCheck(ctx context.Context, in *Request, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type uidGeneratorClient struct {
	cc grpc.ClientConnInterface
}

func NewUidGeneratorClient(cc grpc.ClientConnInterface) UidGeneratorClient {
	return &uidGeneratorClient{cc}
}

func (c *uidGeneratorClient) Uid(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, UidGenerator_Uid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uidGeneratorClient) HealthCheck(ctx context.Context, in *Request, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, UidGenerator_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UidGeneratorServer is the server API for UidGenerator service.
// All implementations must embed UnimplementedUidGeneratorServer
// for forward compatibility.
type UidGeneratorServer interface {
	Uid(context.Context, *Request) (*Response, error)
	HealthCheck(context.Context, *Request) (*HealthCheckResponse, error)
	mustEmbedUnimplementedUidGeneratorServer()
}

// UnimplementedUidGeneratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUidGeneratorServer struct{}

func (UnimplementedUidGeneratorServer) Uid(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Uid not implemented")
}
func (UnimplementedUidGeneratorServer) HealthCheck(context.Context, *Request) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedUidGeneratorServer) mustEmbedUnimplementedUidGeneratorServer() {}
func (UnimplementedUidGeneratorServer) testEmbeddedByValue()                      {}

// UnsafeUidGeneratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UidGeneratorServer will
// result in compilation errors.
type UnsafeUidGeneratorServer interface {
	mustEmbedUnimplementedUidGeneratorServer()
}

func RegisterUidGeneratorServer(s grpc.ServiceRegistrar, srv UidGeneratorServer) {
	// If the following call pancis, it indicates UnimplementedUidGeneratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UidGenerator_ServiceDesc, srv)
}

func _UidGenerator_Uid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UidGeneratorServer).Uid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UidGenerator_Uid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UidGeneratorServer).Uid(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UidGenerator_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UidGeneratorServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UidGenerator_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UidGeneratorServer).HealthCheck(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// UidGenerator_ServiceDesc is the grpc.ServiceDesc for UidGenerator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UidGenerator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "uid.UidGenerator",
	HandlerType: (*UidGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Uid",
			Handler:    _UidGenerator_Uid_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _UidGenerator_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "main.proto",
}
